version: "3.8"
services:
  nginx:
    image: "nginx:alpine"
    ports:
      - "20000:80"
    volumes:
      - /home/user/voting/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /home/user/voting/:/var/www/html
    restart: always
    depends_on:
      - voting
 
  voting:
    build: 
      dockerfile: ./Dockerfile
    environment:
      - .env
    depends_on:
      - mysql
      - redis
    ports:
      - "9000:9000"
    expose:
      - "9000"
    restart: always
    
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: voting
      MYSQL_DATABASE: voting
      MYSQL_USER: voting
      MYSQL_PASSWORD: voting
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  redis:
    image: "redis:7-alpine"
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always
 
volumes:
  mysql_data:
  redis_data: