version: "3.8"
services:
  postgres:
    image: "postgres:10"
    environment:
      POSTGRES_PASSWORD: DatabasePassword
      POSTGRES_USER: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  
  gocalc:
    build: .
    environment:
      POSTGRES_URI: "postgres://postgres:DatabasePassword@postgres:5432/postgres?sslmode=disable"
    depends_on:
      - postgres
    ports:
      - "7000:7000"
    restart: always
  
  nginx:
    image: "nginx:stable"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - gocalc

volumes:
  db_data:

